FROM centos 
MAINTAINER lihao<310103270@qq.com>

RUN yum install -y gcc vim net-tools automake autoconf libtool make

ONBUILD RUN echo "---------------已安装gcc vim net-tools automake autoconf libtool make------------------------"

CMD /bin/bash

