version: "2"
services:

    nginx_m:
        image: hub.c.163.com/electricight/nginx:1.0
        container_name: nginx_m
        privileged: true
        command: 
            - /bin/bash
            - -c
            - service keepalived start && service nginx start && tail -f /var/log/nginx/error.log        
        volumes:
            - /media/lihao/F/mywork/nginx/share_f/nginx_m/conf/nginx:/etc/nginx
            - /media/lihao/F/mywork/nginx/share_f/nginx_m/conf/keepalived:/etc/keepalived
            - /media/lihao/F/mywork/nginx/share_f/nginx_m/www:/usr/share/nginx/www
        networks:
            default:
                ipv4_address: 172.18.0.2
    nginx_s:
        image: hub.c.163.com/electricight/nginx:1.0
        container_name: nginx_s
        privileged: true
        depends_on:
            - nginx_m
        command: 
            - /bin/bash
            - -c
            - service keepalived start && service nginx start && tail -f /var/log/nginx/error.log         
        volumes:
            - /media/lihao/F/mywork/nginx/share_f/nginx_s/conf/nginx:/etc/nginx
            - /media/lihao/F/mywork/nginx/share_f/nginx_s/conf/keepalived:/etc/keepalived
            - /media/lihao/F/mywork/nginx/share_f/nginx_s/www:/usr/share/nginx/www
        networks:
            default:
                ipv4_address: 172.18.0.3
networks:
    default:
        external:
            name: backend
