version: "2"
services:

    redis_master:
        image: redis
        container_name: redis_master
        privileged: true
        command:
            - /bin/bash
            - -c
            - redis-server /usr/local/redis/etc/redis.conf && tail -f /usr/local/redis/log/redis.log
        volumes:
            - /media/lihao/F/mywork/redis/share_f/conf/master:/usr/local/redis/etc
        networks:
            default:
                ipv4_address: 172.18.0.7
    redis_backup:
        image: redis
        container_name: redis_backup
        privileged: true
        command:
            - /bin/bash
            - -c
            - redis-server /usr/local/redis/etc/redis.conf && tail -f /usr/local/redis/log/redis.log
        volumes:
            - /media/lihao/F/mywork/redis/share_f/conf/backup:/usr/local/redis/etc
        networks:
            default:
                ipv4_address: 172.18.0.8
    redis_sentinel:
        image: redis
        container_name: redis_sentinel
        privileged: true
        command:
            - /bin/bash
            - -c
            - redis-sentinel /usr/local/redis/etc/sentinel.conf && tail -f /usr/local/redis/log/redis.log
        volumes:
            - /media/lihao/F/mywork/redis/share_f/conf/sentinel:/usr/local/redis/etc
        networks:
            default:
                ipv4_address: 172.18.0.9
networks:
    default:
        external:
            name: backend
